apiVersion: v1
kind: Service
metadata:
  name: api-client
  labels:
    app: test-clients
    client: api-client
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    app: test-clients
    client: api-client
  type: ClusterIP
