apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: test-clients
  labels:
    monitoring-key: middleware
    app: test-clients
spec:
  selector:
    matchLabels:
      app: test-clients
  endpoints:
  - port: metrics
  namespaceSelector:
    matchLabels:
      monitoring-key: middleware
